### ISSUE TITLE
quasar dev 运行不起来

### ISSUE THREAD

**Issue by liangzhiyuan2015** [wjkang/vue-quasar-admin#1]
![image](https://user-images.githubusercontent.com/13427595/40277841-95ceca46-5c58-11e8-944f-efb9c542d3ea.png)

**Comment by wjkang** [comment]
@liangzhiyuan2015  
`npm install -g vue-cli`

`npm install -g quasar-cli`

**Comment by liangzhiyuan2015** [comment]
好，我刚刚也发现了这个前提条件，谢谢提醒！
